INSERT INTO STUDIO VALUES (STUDIO_ID_GEN.NEXTVAL, 'STUDIO1');
INSERT INTO PRODUCER VALUES (PRODUCER_ID_GEN.NEXTVAL, 'PRODUCER1');

INSERT INTO MOVIE VALUES (MOVIE_ID_GEN.NEXTVAL, 'Movie title', 1989, FALSE);

INSERT INTO MOVIE_PRODUCERS(MOVIES_ID, PRODUCERS_ID)
SELECT M.ID, P.ID FROM MOVIE M, PRODUCER P;

INSERT INTO MOVIE_STUDIOS (MOVIES_ID, STUDIOS_ID)
SELECT M.ID, S.ID FROM MOVIE M, STUDIO S;