INSERT INTO STUDIO (ID, NAME) VALUES (1, 'STUDIO1');

INSERT INTO PRODUCER (ID, NAME) VALUES
(1, 'PRODUCER1'), --1 MOVIE - SINGLE AWARD WINNING MOVIE
(2, 'PRODUCER2'), --2 MOVIES - TWO AWARD WINNING MOVIES
(3, 'PRODUCER3'); --2 MOVIES - SINGLE AWARD WINNING AND SINGLE NON AWARD WINNING

INSERT INTO MOVIE (ID, TITLE, YEAR, WINNER) VALUES
(1, 'Movie 1', 1989, TRUE),
(2, 'Movie 2', 1990, TRUE),
(3, 'Movie 3', 1991, TRUE),
(4, 'Movie 4', 1992, TRUE),
(5, 'Movie 5', 1993, FALSE);

INSERT INTO MOVIE_PRODUCERS(MOVIES_ID, PRODUCERS_ID)
VALUES (1, 1), (2, 2), (3, 2), (4, 3), (5, 3);

INSERT INTO MOVIE_STUDIOS (MOVIES_ID, STUDIOS_ID)
VALUES (1, 1), (2, 1), (3, 1), (4, 1), (5, 1);